//
//  MainViewController.swift
//  ComicQuiz
//
//  Created by Knpblo on 9/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainDisplayLogic: AnyObject
{
  func displaySignIn(viewModel: Main.SignIn.ViewModel)
}

class MainViewController: UIViewController, MainDisplayLogic
{
  var interactor: MainBusinessLogic?
  var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = MainInteractor()
    let presenter = MainPresenter()
    let router = MainRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
      doSignIn()
  }
    
    
  // MARK: Do something
    @IBOutlet weak var nameTextField: UITextField!
    
    @IBAction func SignIn(_ sender: UIButton) {
        doSignIn()
    }
    
  
  func doSignIn()
  {
    let request = Main.SignIn.Request(name: nameTextField.text!)
    interactor?.SignIn(request: request)
  }
  
  func displaySignIn(viewModel: Main.SignIn.ViewModel)
  {
      if viewModel.success{
          router?.routeToHero(segue:nil)
      }
      
      else{
          displayAlert()
      }
  }
    
    
    func displayAlert(){
        let Alert = UIAlertController(title: "Please tell your name", message: "Please tell your name, if you want to go next page.", preferredStyle: .alert)
        
        Alert.addAction(UIAlertAction(title: "Okay", style: .cancel, handler: nil))
        
        self.present(Alert, animated: true)
    }
}
