//
//  MainModels.swift
//  ComicQuiz
//
//  Created by Knpblo on 9/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
  // MARK: Use cases
  
  enum SignIn
  {
    struct Request{
        let name: String
    }
      
    struct Response{
        let success: Bool
    }
      
    struct ViewModel{
        let success: Bool
    }
      
  }
}
