//
//  MainRouter.swift
//  ComicQuiz
//
//  Created by Knpblo on 9/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

    @objc protocol MainRoutingLogic
    {
      func routeToHero(segue: UIStoryboardSegue?)
    }

    protocol MainDataPassing{
      var dataStore: MainDataStore? { get }
    }

    class MainRouter: NSObject, MainRoutingLogic, MainDataPassing{
      weak var viewController: MainViewController?
      var dataStore: MainDataStore?
  
  // MARK: Routing
  
  func routeToHero(segue: UIStoryboardSegue?){
    if let segue = segue {
      let destinationVC = segue.destination as! HeroViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToHero(source: dataStore!, destination: &destinationDS)
    } else {
      let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "HeroViewController") as! HeroViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToHero(source: dataStore!, destination: &destinationDS)
      navigateToHero(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToHero(source: MainViewController, destination: HeroViewController){
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToHero(source: MainDataStore, destination: inout HeroDataStore){
    destination.name = source.name
  }
}
