//
//  QuizRouter.swift
//  ComicQuiz
//
//  Created by Knpblo on 9/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HeroRoutingLogic
{
  func routeToDetail(segue: UIStoryboardSegue?)
}

protocol HeroDataPassing
{
  var dataStore: HeroDataStore? { get }
}

class QuizRouter: NSObject, HeroRoutingLogic, HeroDataPassing
{
  weak var viewController: HeroViewController?
  var dataStore: HeroDataStore?
  
  // MARK: Routing
  
    func routeToDetail(segue: UIStoryboardSegue?){
      if let segue = segue {
        let destinationVC = segue.destination as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(source: dataStore!, destination: &destinationDS)
      } else {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinationVC)
      }
    }

    // MARK: Navigation
    
    func navigateToDetail(source: HeroViewController, destination: DetailViewController){
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetail(source: HeroDataStore, destination: inout DetailDataStore){
        destination.name = source.name
      destination.heroName = source.heroName
    }
  }
