//
//  QuizModels.swift
//  ComicQuiz
//
//  Created by Knpblo on 9/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Hero
{
  // MARK: Use cases
  
      enum SignInName
      {
        struct Request{
        }
          
        struct Response{
            var name: String
        }
          
        struct ViewModel{
            var name: String
        }
      }

        enum Hero{
            case CaptainAmerica
            case IronMan
            case SpiderMan
            case Thor
        }
    
    
      enum SelectHero
      {
        struct Request{
            var hero : Hero
        }
        
        struct Response{
            var hero: Hero
            var heroName: String
            var alterEgo: String
            var heroImage: UIImage
            var heroBG: UIImage
        }
            
        struct ViewModel{
            var heroName: String
            var alterEgo: String
            var heroImage: UIImage
            var heroBG: UIImage
            
            var isCaptainAmericaOpen : Bool
            var isIronManOpen : Bool
            var isSpiderManOpen : Bool
            var isThorOpen : Bool
            
        }
      }
}
