//
//  QuizPresenter.swift
//  ComicQuiz
//
//  Created by Knpblo on 9/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HeroPresentationLogic
{
  func presentSignInName(response: Hero.SignInName.Response)
  func presentSelectedHero(response: Hero.SelectHero.Response)
}

class HeroPresenter: HeroPresentationLogic
{
  weak var viewController: HeroDisplayLogic?
  
  // MARK: Do something
  
  func presentSignInName(response: Hero.SignInName.Response)
  {
      let Welcome = "Welcome \(response.name), Nice to meet you"
      let viewModel = Hero.SignInName.ViewModel(name: Welcome)
      viewController?.displaySignInName(viewModel: viewModel)
  }
    
    func presentSelectedHero(response: Hero.SelectHero.Response)
    {
        let HeroName = "Hero's name is \(response.heroName)."
        let AlterEgo = "Hero's real name is \(response.alterEgo)."
        let HeroImage = response.heroImage
        let HeroBG = response.heroBG
        
        let isCaptainAmericaOpen : Bool = response.hero == .CaptainAmerica
        let isIronManOpen : Bool = response.hero == .IronMan
        let isSpiderManOpen : Bool = response.hero == .SpiderMan
        let isThorOpen : Bool = response.hero == .Thor
        
        let viewModel = Hero.SelectHero.ViewModel(heroName: HeroName, alterEgo: AlterEgo, heroImage: HeroImage, heroBG: HeroBG, isCaptainAmericaOpen: isCaptainAmericaOpen, isIronManOpen: isIronManOpen, isSpiderManOpen: isSpiderManOpen, isThorOpen: isThorOpen)
        viewController?.displaySelectedHero(viewModel: viewModel)
    }
}
