//
//  DetailInteractor.swift
//  ComicQuiz
//
//  Created by Knpblo on 10/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
  func DetailName(request: Detail.DetailName.Request)
}

protocol DetailDataStore
{
  var name: String {get set}
  var heroName: String { get set }
  var refName: String { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  var presenter: DetailPresentationLogic?
  var worker: DetailWorker?
  var name: String = ""
  var heroName: String = ""
  var refName: String = ""
  
  // MARK: Do something
  
  func DetailName(request: Detail.DetailName.Request)
  {
      let response = Detail.DetailName.Response(name: name, refName: refName, heroName: heroName)
    presenter?.presentDetailName(response: response)
  }
}
