//
//  DetailModels.swift
//  ComicQuiz
//
//  Created by Knpblo on 10/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail
{
  // MARK: Use cases
  
    enum DetailName
    {
      struct Request{
      }
        
      struct Response{
          var name: String
          var refName: String
          var heroName: String
      }
        
      struct ViewModel{
          var name: String
          var refName: String
          var heroName: String
      }
    }
}
