//
//  DetailPresenter.swift
//  ComicQuiz
//
//  Created by Knpblo on 10/11/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentDetailName(response: Detail.DetailName.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
  func presentDetailName(response: Detail.DetailName.Response)
  {
      let SignInName = "\(response.name)"
      let SelectedName = "\(response.heroName)"
      let RefName = "\(response.name)! We shall meet again !!!"
      let viewModel = Detail.DetailName.ViewModel(name: SignInName, refName: RefName, heroName: SelectedName)
    viewController?.displayDetailName(viewModel: viewModel)
  }
}
